device:
  base_dir: /home/ppwang/Projects/CPLFN
  base_data_dir: ${device.base_dir}/data

case_name: trex
exp_name: test
base_exp_dir: ${device.base_dir}/exp/${case_name}/${exp_name}
recording: [./*.py, ./modules/*.py, ./modules/*/*.py]

mode: train
is_continue: false

train:
  learning_rate: 1e-4
  learning_rate_alpha: 2.5e-2
  lr_anneal_type: cosine

  mile_stones: [ 0, 6000, 12500, 25000, 50000, 100000 ]
  sub_div_inputs: [ true, true, true, true, true ]
  sub_div_outputs: [ true, true, true, true, true ]
  end_iter: 100000

  render_batch_size: 16384
  vis_down_level: 1

  save_freq: 200000
  vis_freq: 5000
  val_freq: 50000
  video_freq: 50000
  report_freq: 10000
  tsboard_freq: 10

Regularizer:
  batch_size: 4096
  reg_weight: 1.
  reg_window_begin: 6000
  reg_window_end: 50000
  color_weight: 1e-2
  density_weight: 1e-3
  r_alpha: 0.
  sml1_beta: 0.5

PixelSupervisor:
  color_weight: 1.
  gray_weight: 0.
  batch_size: 16384

LLFFDataset:
  data_dir: ${device.base_data_dir}/${case_name}/
  target_width: 1008
  factor: 4

ProLiFRenderer:
  embedder_conf:
    n_samples: ${ProLiFRenderer.weight_conf.d_subfields}
  weight_conf:
    d_subfields: 16
    d_in: 2
    d_out: 4
    d_hidden: 32
    n_layers: 9
    skips: [4]
    first_omega_0: 30.0
    omega_0: 30.0
    bias_mul: 1.0
  field_conf:
    weight_norm: true
    skips: ${ProLiFRenderer.weight_conf.skips}
    d_hidden: ${ProLiFRenderer.weight_conf.d_hidden}
    act_conf:
      first_omega_0: ${ProLiFRenderer.weight_conf.first_omega_0}
      omega_0: ${ProLiFRenderer.weight_conf.omega_0}
    activation: sine