from modules.supervisor.clip_supervisor import ClipSupervisor
from modules.supervisor.patch_supervisor import PatchSupervisor
from modules.supervisor.pixel_supervisor import PixelSupervisor
from modules.supervisor.regularizer import Regularizer
